### ISSUE TITLE
Leftover merge conflict in user guide

### ISSUE THREAD

**Issue by k-l-a** [CS2103AUG2017-W13-B2/main#102]
![image](https://user-images.githubusercontent.com/30980251/32363495-9bcf73cc-c0aa-11e7-93a9-922e9d71b44c.png)

**Comment by k-l-a** [comment]
![image](https://user-images.githubusercontent.com/30980251/32363520-b8d5901e-c0aa-11e7-8933-1be8aa6cd9ce.png)

Which causes formatting error in the add command section

**Comment by pjunwei95** [comment]
Thank you for your feedback! We will look into this!
