### ISSUE TITLE
Autocomplete can be quite frustrating

### ISSUE THREAD

**Issue by reginleiff** [CS2103AUG2017-W13-B2/main#110]
Some overlapping commands are frustrating to use with autocomplete, for example `findtag` and `find`.

Perhaps one simple solution is to set very distinct names for these kind of commands.

**Comment by k-l-a** [comment]
To add, autocomplete was also sometimes frustrating if I linger on the first letter (causing the autocomplete to show) and then quickly finish the command and try to press enter. It will autocomplete instead of executing the command typed.

**Comment by pjunwei95** [comment]
Thank you for your feedback! We will look into this!
