### ISSUE TITLE
code quality comments for ChenXiaoman

### ISSUE THREAD

**Issue by okkhoy** [CS2103AUG2017-W13-B2/main#127]
![image](https://user-images.githubusercontent.com/1023494/32642303-52a3aa10-c60e-11e7-88ac-cf68ab06e630.png)
- header comments don't follow the format we specify

@ChenXiaoman  fya

**Comment by ChenXiaoman** [comment]
Thank you! I will fix that.
May I ask whether there are any other major quality deficits besides this one? 😛

**Comment by okkhoy** [comment]
I would have indicated anything that I come across.. if there is nothing much, feel proud, your code quality is good :100: :clap:
