### ISSUE TITLE
code quality comments for yangminxingnus

### ISSUE THREAD

**Issue by okkhoy** [CS2103AUG2017-W13-B2/main#128]
![image](https://user-images.githubusercontent.com/1023494/32642605-775c071a-c610-11e7-9c86-bd30a8cb55ea.png)
- don't retain commented out code

![image](https://user-images.githubusercontent.com/1023494/32642624-8b1450f0-c610-11e7-95e5-46c21081384c.png)
- two things here:
1. header comment without a description is not very useful. hence add a brief description
2. choose a better name for the method; follow the convention to choose name for boolean returning methods

@yangminxingnus fya

**Comment by yangminxingnus** [comment]
thanks, fixed already
