### ISSUE TITLE
code quality comments for RonakLakhotia

### ISSUE THREAD

**Issue by okkhoy** [CS2103AUG2017-W13-B2/main#129]
![image](https://user-images.githubusercontent.com/1023494/32642906-6c41e776-c612-11e7-9d16-2ba34b10eb14.png)
- have some description in the header comments. it is not very useful to have empty header comments

![image](https://user-images.githubusercontent.com/1023494/32642933-9390fc40-c612-11e7-8471-9b8f811756c5.png)
- a better comment would be `Returns true if ...`

![image](https://user-images.githubusercontent.com/1023494/32642948-ab9c91a0-c612-11e7-83e0-8e392afdb81d.png)
- seriously?!? :stuck_out_tongue: 

@RonakLakhotia FYA

**Comment by RonakLakhotia** [comment]
@okkhoy 
1) including some description would mean to describe the method a bit more ?
2) how is the rest of the layout of the code ?
P.S Last one , I was just checking how to collate :P
