### ISSUE TITLE
code quality comments for pjunwei95

### ISSUE THREAD

**Issue by okkhoy** [CS2103AUG2017-W13-B2/main#130]
![image](https://user-images.githubusercontent.com/1023494/32642986-001fc7ec-c613-11e7-9509-23549f031ab0.png)
- header comment doesn't follow the convention we specify

![image](https://user-images.githubusercontent.com/1023494/32643003-242cb62c-c613-11e7-8f7b-2ec718905721.png)
- either the class name or the header comment is inconsistent with the other

![image](https://user-images.githubusercontent.com/1023494/32643021-4a88aa74-c613-11e7-8588-c8510dafe963.png)
- please fix the collation or remove the comment

@pjunwei95  fya

**Comment by pjunwei95** [comment]
Thank you very much!
