### ISSUE TITLE
Fix WebView text issue

### ISSUE THREAD

**Issue by caoliangnus** [CS2103AUG2017-W13-B2/main#132]
Hi, I have a way to make the web view text display properly. 
You can refer [here](https://github.com/nus-cs2103-AY1718S1/forum/issues/208), or you can refer to the picture below. 

![image](https://user-images.githubusercontent.com/30979259/32670137-d5cc9540-c67d-11e7-8383-59ee08b7fdd7.png)

![image](https://user-images.githubusercontent.com/30979259/32670123-c73ce444-c67d-11e7-9de7-25c34d81c502.png)

**Comment by ChenXiaoman** [comment]
Thank you!
