### ISSUE TITLE
Everything on track to submit?

### ISSUE THREAD

**Issue by okkhoy** [CS2103AUG2017-W13-B2/main#148]
Everything on track to submit? Remember to read submission instructions carefully and plan to finish submissions at least few hours before the deadline. All the best :+1:

**Comment by pjunwei95** [comment]
Thanks! Just asking one question, its sufficient to upload a pdf version of our portfolio to IVLE right?

**Comment by okkhoy** [comment]
please follow the instructions. i haven't read the requirement
