### ISSUE TITLE
As a user I want to be able to Delete Tags

### ISSUE THREAD

**Issue by RonakLakhotia** [CS2103AUG2017-W13-B2/main#50]
So that I can change the tags I assign to the people in my contact list.

**Comment by RonakLakhotia** [comment]
@pjunwei95 Can be done by this week right?

**Comment by pjunwei95** [comment]
Yup

**Comment by pjunwei95** [comment]
Done. Am closing this thread

**Comment by RonakLakhotia** [comment]
Cool Thanks
