### ISSUE TITLE
Some images in the user guide doesn't seem to be there

### ISSUE THREAD

**Issue by k-l-a** [CS2103AUG2017-W13-B2/main#98]
![image](https://user-images.githubusercontent.com/30980251/32363087-766eced6-c0a8-11e7-86a3-d79d0a9ff14b.png)

I believe there should be an image there?

![image](https://user-images.githubusercontent.com/30980251/32363099-85ee0804-c0a8-11e7-9140-eb532fe29acd.png)

and there also

**Comment by pjunwei95** [comment]
Thank you for your feedback! We will look into this!
